Continue even if starting one VM failed

diff --git a/xen-tender b/xen-tender
--- a/xen-tender
+++ b/xen-tender
@@ -18,6 +18,6 @@ VMS=$(/usr/sbin/drbd-overview | grep Primary | cut -d ':' -f 2 | cut -d '_' -f 1
 echo "$1" | sed 's/,/\n/g' | while read -r LINE; do
 	if [ "$(echo "$VMS" | grep -cE "^$LINE$")" -ne "1" ]; then
 		echo "Need to start $LINE"
-		/usr/local/sbin/xen-start $LINE
+		/usr/local/sbin/xen-start $LINE || echo "Could not start $LINE. Continuing anyway."
 	fi
 done
